spring:
  application:
    name: job-radar

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/opc_job_radar}
    username: ${DB_USERNAME:opc}
    password: ${DB_PASSWORD:opc}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true